In [37]:
from pathlib import Path
import h5py
from typing import Tuple, Dict
import numpy as np

INPUT_PATH = Path("../data/results/testing_fixtures_maize/maize_inputs.h5")
print(INPUT_PATH.resolve())  # Te muestra la ruta absoluta
print(INPUT_PATH.exists())  # T

C:\Users\benjamin\Desktop\risk_and_yield\data\results\testing_fixtures_maize\maize_inputs.h5
True


In [43]:
def load_all_arrays_from_h5(
    path: str | Path,
) -> Dict[str, Dict[str, np.ndarray]]:
    """Carga todos los grupos y datasets de un archivo HDF5 a memoria.

    Parameters
    ----------
    path : str
        Ruta del archivo HDF5.

    Returns
    -------
    Dict[str, Dict[str, np.ndarray]]
        Diccionario anidado: {grupo: {dataset: array}}
    """
    data: Dict[str, Dict[str, np.ndarray]] = {}
    with h5py.File(path, "r") as f:
        for group_name in f.keys():
            group = f[group_name]
            group_dict: Dict[str, np.ndarray] = {}
            for ds_name, ds in group.items():
                if isinstance(ds, h5py.Dataset):
                    group_dict[ds_name] = ds[:]  # cargar a numpy
            data[group_name] = group_dict
    return data

In [44]:
data = load_all_arrays_from_h5(INPUT_PATH.resolve())

In [ ]:
soil_keys = data["soil"].keys()
weather_keys = data["weather"].keys()

In [57]:
print(weather_keys)
print(soil_keys)

dict_keys(['et0', 'par', 'precip', 'temp'])
dict_keys(['dds0', 'lat', 'lon', 'mask_maize', 'mask_soy', 'water0'])


In [53]:
data["weather"]["et0"][:20]

array([1.60165144, 1.38806221, 1.92311187, 2.40184275, 2.01233024,
       0.70850647, 0.24659994, 1.87858045, 1.31209809, 0.81067803,
       2.19627038, 2.12287321, 2.57087704, 2.61107689, 2.56842216,
       2.91665965, 2.33954623, 2.51504941, 1.45968165, 2.34738826])

In [54]:
data["weather"]["par"][:20]

array([10.816416,  9.359712, 11.379744, 14.387328, 11.064384,  5.68512 ,
        3.449088, 12.384576,  8.642592,  6.189696, 12.438144, 12.731904,
       14.684544, 14.097024, 14.656032, 14.694048, 12.032064, 12.76128 ,
        8.001504, 13.90608 ])

In [55]:
data["weather"]["precip"][:20]

array([ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  9.4 ,  0.  , 11.43,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.76,
        1.78,  0.  ])

In [56]:
data["weather"]["temp"][:20]

array([25.8, 24.9, 25.5, 27.1, 28.4, 24.2, 20.3, 24.8, 23.7, 22. , 25.6,
       24.2, 26.8, 26.9, 28.6, 30.6, 35. , 29.4, 30.5, 33.7])